<?php

namespace Database\Seeders;

use App\Models\Livro;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LivroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'posicao' => 1,
                'nome' => 'Gênesis',
                'abreviacao' => 'gn',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 2,
                'nome' => 'Êxodo',
                'abreviacao' => 'ex',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 3,
                'nome' => 'Levítico',
                'abreviacao' => 'lv',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 4,
                'nome' => 'Números',
                'abreviacao' => 'nm',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 5,
                'nome' => 'Deuteronômio',
                'abreviacao' => 'dt',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 6,
                'nome' => 'Josué',
                'abreviacao' => 'js',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 7,
                'nome' => 'Juízes',
                'abreviacao' => 'jz',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 8,
                'nome' => 'Rute',
                'abreviacao' => 'rt',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 9,
                'nome' => '1º Samuel',
                'abreviacao' => '1sm',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 10,
                'nome' => '2º Samuel',
                'abreviacao' => '2sm',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 11,
                'nome' => '1º Reis',
                'abreviacao' => '1rs',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 12,
                'nome' => '2º Reis',
                'abreviacao' => '2rs',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 13,
                'nome' => '1º Crônicas',
                'abreviacao' => '1cr',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 14,
                'nome' => '2º Crônicas',
                'abreviacao' => '2cr',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 15,
                'nome' => 'Esdras',
                'abreviacao' => 'ed',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 16,
                'nome' => 'Neemias',
                'abreviacao' => 'ne',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 17,
                'nome' => 'Ester',
                'abreviacao' => 'et',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 18,
                'nome' => 'Jó',
                'abreviacao' => 'jo',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 19,
                'nome' => 'Salmos',
                'abreviacao' => 'sl',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 20,
                'nome' => 'Provérbios',
                'abreviacao' => 'pv',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 21,
                'nome' => 'Eclesiastes',
                'abreviacao' => 'ec',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 22,
                'nome' => 'Cânticos',
                'abreviacao' => 'ct',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 23,
                'nome' => 'Isaías',
                'abreviacao' => 'is',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 24,
                'nome' => 'Jeremias',
                'abreviacao' => 'jr',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 25,
                'nome' => 'Lamentações',
                'abreviacao' => 'lm',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 26,
                'nome' => 'Ezequiel',
                'abreviacao' => 'ez',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 27,
                'nome' => 'Daniel',
                'abreviacao' => 'dn',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 28,
                'nome' => 'Oséias',
                'abreviacao' => 'os',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 29,
                'nome' => 'Joel',
                'abreviacao' => 'jl',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 30,
                'nome' => 'Amós',
                'abreviacao' => 'am',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 31,
                'nome' => 'Obadias',
                'abreviacao' => 'ob',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 32,
                'nome' => 'Jonas',
                'abreviacao' => 'jn',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 33,
                'nome' => 'Miquéias',
                'abreviacao' => 'mq',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 34,
                'nome' => 'Naum',
                'abreviacao' => 'na',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 35,
                'nome' => 'Habacuque',
                'abreviacao' => 'hc',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 36,
                'nome' => 'Sofonias',
                'abreviacao' => 'sf',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 37,
                'nome' => 'Ageu',
                'abreviacao' => 'ag',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 38,
                'nome' => 'Zacarias',
                'abreviacao' => 'zc',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 39,
                'nome' => 'Malaquias',
                'abreviacao' => 'ml',
                'testamento_id' => 1,
                'versao_id' => 1,
            ],
            [
                'posicao' => 40,
                'nome' => 'Mateus',
                'abreviacao' => 'mt',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 41,
                'nome' => 'Marcos',
                'abreviacao' => 'mc',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 42,
                'nome' => 'Lucas',
                'abreviacao' => 'lc',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 43,
                'nome' => 'João',
                'abreviacao' => 'ja',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 44,
                'nome' => 'Atos',
                'abreviacao' => 'at',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 45,
                'nome' => 'Romanos',
                'abreviacao' => 'rm',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 46,
                'nome' => '1ª Coríntios',
                'abreviacao' => '1co',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 47,
                'nome' => '2ª Coríntios',
                'abreviacao' => '2co',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 48,
                'nome' => 'Gálatas',
                'abreviacao' => 'gl',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 49,
                'nome' => 'Efésios',
                'abreviacao' => 'ef',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 50,
                'nome' => 'Filipenses',
                'abreviacao' => 'fp',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 51,
                'nome' => 'Colossenses',
                'abreviacao' => 'cl',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 52,
                'nome' => '1ª Tessalonicenses',
                'abreviacao' => '1ts',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 53,
                'nome' => '2ª Tessalonicenses',
                'abreviacao' => '2ts',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 54,
                'nome' => '1ª Timóteo',
                'abreviacao' => '1tm',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 55,
                'nome' => '2ª Timóteo',
                'abreviacao' => '2tm',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 56,
                'nome' => 'Tito',
                'abreviacao' => 'tt',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 57,
                'nome' => 'Filemom',
                'abreviacao' => 'fm',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 58,
                'nome' => 'Hebreus',
                'abreviacao' => 'hb',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 59,
                'nome' => 'Tiago',
                'abreviacao' => 'tg',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 60,
                'nome' => '1ª Pedro',
                'abreviacao' => '1pe',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 61,
                'nome' => '2ª Pedro',
                'abreviacao' => '2pe',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 62,
                'nome' => '1ª João',
                'abreviacao' => '1jo',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 63,
                'nome' => '2ª João',
                'abreviacao' => '2jo',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 64,
                'nome' => '3ª João',
                'abreviacao' => '3jo',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 65,
                'nome' => 'Judas',
                'abreviacao' => 'jd',
                'testamento_id' => 2,
                'versao_id' => 1,
            ],
            [
                'posicao' => 66,
                'nome' => 'Apocalipse',
                'abreviacao' => 'ap',
                'testamento_id' => 2,
                'versao_id' => 1,
            ]
        ];
        Livro::insert($data);
    }
}
